Rails:
  Enabled: true

Metrics/LineLength:
  Max: 100

Style/TrailingWhitespace:
  Enabled: false

AllCops:
  Exclude:
    - vendor/**/*
    - test/fixtures/**/**
    - coverage/**/*
    - bin/**/*
    - doc/**/*
    - config/**/*
    - db/**/*