version: '2'
services:
  db:
    image: postgres:9.6
    ports:
      - '5432:5432'
  gem:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - $PWD:/guts
    ports:
      - '3000:3000'
    depends_on:
      - db